### ISSUE TITLE
Odd behavior in Julia 1.8.5 on Linux Mint 20.3

### ISSUE THREAD

**Issue by gmlewis** [bkamins/JuliaForDataAnalysis#6]
This seems really odd... any ideas what I'm doing wrong?

```bash
glenn@glenn-OMEN-875 ~/src/github.com/bkamins/JuliaForDataAnalysis (main) $ julia --version
julia version 1.8.5
glenn@glenn-OMEN-875 ~/src/github.com/bkamins/JuliaForDataAnalysis (main) $ LD_LIBRARY_PATH="" julia -q --project
(JuliaForDataAnalysis) pkg> instantiate
┌ Warning: The active manifest file has dependencies that were resolved with a different julia version (1.7.3). Unexpected behavior may occur.
└ @ ~/src/github.com/bkamins/JuliaForDataAnalysis/Manifest.toml:0

julia> include("ch02.jl")
ERROR: LoadError: cannot document the following expression:

0.1

Stacktrace:
 [1] error(::String, ::String)
   @ Base ./error.jl:44
 [2] top-level scope
   @ ~/src/github.com/bkamins/JuliaForDataAnalysis/ch02.jl:9
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [4] top-level scope
   @ REPL[2]:1
in expression starting at /home/glenn/src/github.com/bkamins/JuliaForDataAnalysis/ch02.jl:9

julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 8 on 16 virtual cores
Environment:
  LD_LIBRARY_PATH = 
  JULIA_NUM_THREADS = 8

julia> 
```

**Comment by bkamins** [comment]
The problem is that you are trying to `include` this file, which is not how it is meant to be used. The reason is that it contains multiple expressions (some of which even error on purpose). They should be copy-pasted to REPL as you read the book. There are comments to which parts of the book given lines refer.

If you want to load everything in one shot maybe you would find it easier to work with the Jupyter Notebook file that is contained in /lectures/lecture02.ipynb.

---

Now to explain you what happens in your particular case. When you load a file using `include` the part of code:
```
"Hello world!"
0.1
```
is interpreted as you would want to add documentation string `"Hello world!"` to 0.1 literal. Which is not allowed. This is explained in this section of the Julia Manual: https://docs.julialang.org/en/v1/manual/documentation/#Writing-Documentation.

To avoid the confusion you had I have updated the files so that they do not generate this error. Still you will not be able to `include` this file without error as later in the file there is an expression that errors on purpose.

**Comment by gmlewis** [comment]
Sorry for the noise, and thank you for the explanation!  I appreciate it.

**Comment by bkamins** [comment]
No problem. Please ask whenever you have any questions.
